export const countryData = [
  {
    id: 1,
    name: "UK",
    realName: "United Kingdom (UK)",
    slugName:'united-kingdom',
    capital: "London",
    language: "English",
    Universities: 500,
    currency: "British Pound Sterling (GBP)",
    intake: "January, September",
    postStudyWork: "18 months",
    avgTuitionFee: "EUR 10,000 - EUR 25,000 per year",
    title1: "Why Study in the UK & Its Global Advantages",
    about:
      "The United Kingdom is home to some of the world’s most prestigious universities, including the University of Oxford, the University of Cambridge, and Imperial College London. It offers a rich blend of history, culture, and innovation. Students experience diverse communities, vibrant cities, and globally recognized academic standards across various disciplines and research fields.",
    whyThisCountry:
      "Studying in the United Kingdom provides internationally respected qualifications and strong career prospects. Universities emphasize critical thinking, practical learning, and research excellence. With shorter course durations and multicultural exposure, students gain global perspectives and valuable networks. A UK degree enhances employability and opens doors to opportunities across industries worldwide.",
    topUniversities: [
      "University of Bristol",
      "University of Southampton",
      "University of Glasgow",
      "University of Leeds",
      "University of Birmingham",
      "Durham University",
      "University of Sheffield",
      "University of Nottingham",
      "Newcastle University",
      "Queen Mary University of London",
    ],
     courses: [
      { courseName: "Artificial Intelligence & Machine Learning", degrees: ["BSc", "MSc"] },
      { courseName: "Data Science & Analytics", degrees: ["BSc", "MSc"] },
      { courseName: "Business Analytics", degrees: ["BSc", "MSc"] },
      { courseName: "Cyber Security", degrees: ["BSc", "MSc"] },
      { courseName: "Finance & FinTech", degrees: ["BSc", "MSc"] },
      { courseName: "Healthcare & Nursing", degrees: ["BSc", "MSc"] },
      { courseName: "Law", degrees: ["LLB", "LLM"] },
      { courseName: "Digital Marketing", degrees: ["BSc", "MSc"] }
    ]
  },
  {
    id: 2,
    name: "Australia",
    slugName:'australia',
    capital: "Canberra",
    language: "English",
    Universities: 500,
    currency: "Australian Dollar (AUD)",
    intake: "February, July, November",
    postStudyWork: "2 - 4 years",
    avgTuitionFee: "AUD 20,000 - AUD 45,000 per year",
    title1: "Why Study in Australia & Its Global Advantages",
    about:
      "Australia is known for its world-class universities, vibrant cities, and stunning natural landscapes. Institutions such as the University of Melbourne and the Australian National University offer globally recognized programs. Students enjoy a high quality of life, multicultural communities, and strong support services in a safe, welcoming environment.",
    whyThisCountry:
      "Studying in Australia provides excellent research opportunities and practical learning experiences. The country encourages innovation and industry collaboration, helping students gain job-ready skills. With post-study work options and a strong economy, graduates benefit from valuable international exposure and enhanced global career prospects.",
    topUniversities: [
      "The University of New South Wales, Sydney",
      "University of Technology Sydney",
      "The University of Queensland, Brisbane",
      "RMIT, Melbourne",
      "Monash University",
      "Macquarie University, Sydney",
      "The University of Western Australia, Perth",
      "University of Wollongong",
      "Adelaide University",
      "Deakin University",
    ],
      courses: [
      { courseName: "Nursing & Healthcare", degrees: ["BSc", "MSc"] },
      { courseName: "Information Technology", degrees: ["BSc", "MSc"] },
      { courseName: "Cyber Security", degrees: ["BSc", "MSc"] },
      { courseName: "Civil Engineering", degrees: ["BEng", "MEng"] },
      { courseName: "Accounting & Finance", degrees: ["BCom", "MCom"] },
      { courseName: "Hospitality Management", degrees: ["BBA", "MBA"] },
      { courseName: "Construction Management", degrees: ["BSc", "MSc"] },
      { courseName: "Environmental Science", degrees: ["BSc", "MSc"] }
    ]
  },
  {
    id: 3,
    name: "Canada",
    slugName:'canada',
    capital: "Ottawa",
    language: "English",
    Universities: 500,
    currency: "Canadian Dollar (CAD)",
    title1: "Why Choose Canada for Higher Education",
    intake: "January, May, September",
    postStudyWork: "Up to 3 years",
    avgTuitionFee: "CAD 15,000 - CAD 35,000 per year",
    about:
      "Canada is celebrated for its high academic standards and inclusive society. Universities like the University of Toronto and McGill University are globally ranked and research-focused. The country offers a safe, multicultural environment where students experience diverse cultures, beautiful landscapes, and modern cities.",
    whyThisCountry:
      "Studying in Canada provides affordable education compared to many other destinations, along with strong career pathways. Institutions emphasize practical learning and research excellence. With post-graduation work permits and immigration opportunities, students gain valuable experience and long-term career advantages.",
    topUniversities: [
      "University of Toronto",
      "University of British Columbia",
      "McGill University",
      "University of Alberta",
      "McMaster University",
      "University of Montreal",
      "University of Waterloo",
      "Western University",
      "University of Calgary",
      "Queen’s University",
    ],
     courses: [
      { courseName: "Artificial Intelligence", degrees: ["BSc", "MSc"] },
      { courseName: "Data Analytics", degrees: ["BSc", "MSc"] },
      { courseName: "Cyber Security", degrees: ["BSc", "MSc"] },
      { courseName: "Healthcare & Nursing", degrees: ["BSc", "MSc"] },
      { courseName: "Project Management", degrees: ["BBA", "MBA"] },
      { courseName: "Business Management", degrees: ["BBA", "MBA"] },
      { courseName: "Renewable Energy", degrees: ["BSc", "MSc"] },
      { courseName: "Supply Chain Management", degrees: ["BBA", "MBA"] }
    ]
  },
  {
    id: 4,
    name: "Germany",
    slugName:'germany',
    capital: "Berlin",
    language: "German",
    Universities: 500,
    currency: "Euro (EUR)",
    title1: "Why Study in Germany & Academic Excellence",
    intake: "April, October",
    postStudyWork: "18 months",
    avgTuitionFee: "EUR 0 - EUR 3,000 per year",
    about:
      "Germany is known for its strong engineering, technology, and research-focused education system. Universities such as the Technical University of Munich offer high-quality programs, many with low or no tuition fees. Students enjoy a rich cultural heritage and a strong economy.",
    whyThisCountry:
      "Studying in Germany provides excellent career prospects, especially in engineering and innovation-driven industries. The country emphasizes practical training and research excellence. With affordable living costs and global recognition, graduates gain competitive skills and international career opportunities.",
    topUniversities: [
      "Lancaster University, Leipzig",
      "Constructor University",
      "EU Business School (Germany)",
      "International School of Management",
      "Arden University Berlin Study Center",
      "SRH Berlin University of Applied Sciences",
      "CBS International Business School",
      "GISMA Business School Hochschule",
      "University of Europe for Applied Sciences",
      "EBS University",
    ],
     courses: [
      { courseName: "Automotive Engineering", degrees: ["BEng", "MEng"] },
      { courseName: "Mechanical Engineering", degrees: ["BEng", "MEng"] },
      { courseName: "Artificial Intelligence", degrees: ["BSc", "MSc"] },
      { courseName: "Data Science", degrees: ["BSc", "MSc"] },
      { courseName: "Robotics", degrees: ["BEng", "MEng"] },
      { courseName: "Renewable Energy Engineering", degrees: ["BEng", "MEng"] },
      { courseName: "Business Management", degrees: ["BBA", "MBA"] },
      { courseName: "Industrial Engineering", degrees: ["BEng", "MEng"] }
    ]
  },
  {
    id: 5,
    name: "USA",
    realName: "United States (USA)",
    slugName:'united-states',
    capital: "Washington, D.C",
    language: "English",
    Universities: 500,
    currency: "United States Dollar (USD)",
    title1: "Why Study in the USA & Career Opportunities",
    intake: "January, May, August",
    postStudyWork: "1 - 3 years (OPT)",
    avgTuitionFee: "USD 20,000 - USD 50,000 per year",
    about:
      "The United States hosts many of the world’s top universities, including Harvard University and Stanford University. It offers cutting-edge research facilities, diverse academic programs, and vibrant campus life. Students benefit from exposure to innovation, entrepreneurship, and global networking opportunities.",
    whyThisCountry:
      "Studying in the USA enhances critical thinking, leadership, and professional development. Universities focus on flexibility and interdisciplinary learning. With strong industry connections and internship opportunities, students gain practical skills and global recognition, boosting employability across international markets.",
    topUniversities: [
      "Harvard University",
      "Stanford University",
      "Massachusetts Institute of Technology (MIT)",
      "University of California, Berkeley",
      "University of California, Los Angeles (UCLA)",
      "University of Chicago",
      "Columbia University",
      "New York University (NYU)",
      "University of Pennsylvania",
      "University of Michigan",
    ],
     courses: [
      { courseName: "Computer Science", degrees: ["BSc", "MS"] },
      { courseName: "Data Science", degrees: ["BSc", "MS"] },
      { courseName: "Artificial Intelligence", degrees: ["BSc", "MS"] },
      { courseName: "Business Administration", degrees: ["BBA", "MBA"] },
      { courseName: "Robotics & Automation", degrees: ["BSc", "MS"] },
      { courseName: "Biotechnology", degrees: ["BSc", "MS"] },
      { courseName: "Cloud Computing", degrees: ["BSc", "MS"] },
      { courseName: "Software Engineering", degrees: ["BSc", "MS"] }
    ]
  },
  {
    id: 6,
    name: "France",
    slugName:'france',
    capital: "Paris",
    language: "French",
    Universities: 500,
    currency: "Euro (EUR)",
    title1: "Why Choose France for International Education",
    intake: "January, September",
    postStudyWork: "2 years",
    avgTuitionFee: "EUR 3,000 - EUR 20,000 per year",
    about:
      "France is renowned for its academic excellence, cultural heritage, and global influence. Institutions like Sorbonne University provide high-quality education across diverse disciplines. Students experience vibrant cities, historic landmarks, and a rich artistic and intellectual environment.",
    whyThisCountry:
      "Studying in France offers exposure to international business, fashion, arts, and technology sectors. Universities promote research, creativity, and global collaboration. With affordable tuition options and access to European markets, students gain valuable international experience and strong career potential.",
    topUniversities: [
      "INSEEC Business School, Paris",
      "NEOMA Business School, Rouen",
      "ESCE International Business School, Paris",
      "ECE Engineering School, Paris",
      "SupdePub School of Creation and Communication, Paris",
      "HEIP, School of International and Political Studies, Paris",
      "Excelia Group, La Rochelle",
      "ICN Business School, Nancy",
      "Kedge Business School, Talence",
    ],
      courses: [
      { courseName: "Luxury Brand Management", degrees: ["BBA", "MBA"] },
      { courseName: "Fashion Management", degrees: ["BBA", "MBA"] },
      { courseName: "Business & International Management", degrees: ["BBA", "MBA"] },
      { courseName: "Artificial Intelligence", degrees: ["BSc", "MSc"] },
      { courseName: "Hospitality Management", degrees: ["BBA", "MBA"] },
      { courseName: "Data Science", degrees: ["BSc", "MSc"] },
      { courseName: "Culinary Arts", degrees: ["Diploma", "Bachelor"] },
      { courseName: "Finance", degrees: ["BCom", "MSc"] }
    ]
  },
  {
    id: 7,
    name: "Ireland",
    slugName:'ireland',
    capital: "Dublin",
    language: "Irish and English",
    Universities: 500,
    currency: "Euro (EUR)",
    title1: "Why Study in Ireland & Industry Connections",
    intake: "January, September",
    postStudyWork: "1 - 2 years",
    avgTuitionFee: "EUR 10,000 - EUR 25,000 per year",
    about:
      "Ireland is home to respected universities such as Trinity College Dublin, known for research and innovation. The country offers a friendly, English-speaking environment with a rich cultural history. Students enjoy modern campuses, scenic landscapes, and a welcoming community.",
    whyThisCountry:
      "Studying in Ireland provides strong links to global technology and pharmaceutical industries. Universities emphasize research and industry collaboration. With post-study work opportunities and access to the European job market, students gain practical skills and enhanced employability.",
    topUniversities: [
      "Trinity College Dublin",
      "University College Dublin",
      "University College Cork",
      "University of Galway",
      "Dublin City University",
      "University of Limerick",
      "Maynooth University",
      "Technological University Dublin",
      "Atlantic Technological University",
      "South-East Technological University",
    ],
   courses: [
      { courseName: "Data Analytics", degrees: ["BSc", "MSc"] },
      { courseName: "Artificial Intelligence", degrees: ["BSc", "MSc"] },
      { courseName: "Pharmaceutical Sciences", degrees: ["BSc", "MSc"] },
      { courseName: "Cyber Security", degrees: ["BSc", "MSc"] },
      { courseName: "Cloud Computing", degrees: ["BSc", "MSc"] },
      { courseName: "Finance", degrees: ["BCom", "MSc"] },
      { courseName: "Business Analytics", degrees: ["BBA", "MSc"] },
      { courseName: "Software Development", degrees: ["BSc", "MSc"] }
    ]
  },
  {
    id: 8,
    name: "New Zealand",
    slugName:'new-zealand',
    capital: "Wellington",
    language: "English, Māori",
    Universities: 500,
    currency: "New Zealand Dollar (NZD)",
    title1: "Why Study in New Zealand & Future Prospects",
    intake: "February, July, November",
    postStudyWork: "Up to 3 years",
    avgTuitionFee: "NZD 22,000 - NZD 40,000 per year",
    about:
      "New Zealand offers high-quality education in a peaceful and welcoming environment. Universities such as the University of Auckland are globally recognized for research and academic excellence. Students enjoy breathtaking natural landscapes and supportive campus communities.",
    whyThisCountry:
      "Studying in New Zealand encourages innovation, critical thinking, and practical learning. The country provides strong student support services and post-study work options. Graduates benefit from internationally respected qualifications and global career opportunities in diverse industries.",
    topUniversities: [
      "University of Auckland",
      "University of Otago",
      "Victoria University of Wellington",
      "University of Canterbury",
      "Massey University",
      "Auckland University of Technology (AUT)",
      "Lincoln University",
      "Waikato University",
    ],
     courses: [
      { courseName: "Agriculture & Agribusiness", degrees: ["BSc", "MSc"] },
      { courseName: "Environmental Science", degrees: ["BSc", "MSc"] },
      { courseName: "Information Technology", degrees: ["BSc", "MSc"] },
      { courseName: "Construction Management", degrees: ["BSc", "MSc"] },
      { courseName: "Nursing", degrees: ["BSc", "MSc"] },
      { courseName: "Hospitality & Tourism", degrees: ["BBA", "MBA"] },
      { courseName: "Data Science", degrees: ["BSc", "MSc"] },
      { courseName: "Engineering", degrees: ["BEng", "MEng"] }
    ]
  },
];
